@ECHO OFF
REM === DO NOT EDIT THIS FILE ===
REM This batch file simply calls the UploadPackage-RunManually.ps1 PowerShell script.
REM You may edit the UploadPackage-RunManually.ps1 script to adjust the settings used to upload the package to the NuGet gallery.
REM Use this script to run the PowerShell script without requiring you to explicitly change your PowerShell Execution Policy settings to allow PowerShell scripts to be ran.
SET THIS_SCRIPTS_DIRECTORY=%~dp0
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '%THIS_SCRIPTS_DIRECTORY%UploadPackage-RunManually.ps1'"